### ISSUE TITLE
Issue with Bitrise Integration step

### ISSUE THREAD

**Issue by moatazeldebsy** [oversecured/oversecured-bitrise-step#2]
Hi, I'm facing an issue when I'm trying to run the Oversecured verified step on Bitrise, I think the step is looking for a `step.sh `script but this doesn't exit in the repository 

<img width="765" alt="Screenshot 2021-10-31 at 21 15 53" src="https://user-images.githubusercontent.com/45570191/139657120-d65331de-0c49-40b1-bca2-fc8bbb5aa65f.png">

**Comment by bagipro** [comment]
Fixed in https://github.com/bitrise-io/bitrise-steplib/pull/3278
